### ISSUE TITLE
Convar indexing error with TTT2

### ISSUE THREAD

**Issue by TimGoll** [TheStig294/zombies_perk_bottles_v2#1]
When using this addon in TTT2 (v0.12b and earlier) this issue appears: 

![image](https://github.com/TheStig294/zombies_perk_bottles_v2/assets/13639408/82f9face-8117-4b6d-a5f5-8f8fb0cb15a4)

As I described on the workshop page, the ConVar seems to be non-existant

**Comment by TheStig294** [comment]
Sorry I tried my best to replicate this but couldn't. I added a blind fix that should hopefully fix this issue.
https://github.com/TheStig294/zombies_perk_bottles_v2/commit/387975bdb3020a77b26ca6f143a5c01e9b4270e2
